# Generated by Django 5.1.6 on 2025-02-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='added',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='published',
            field=models.DateTimeField(blank=True),
        ),
    ]
