# Generated by Django 5.1.6 on 2025-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_datapoint_added_alter_datapoint_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='likelihood',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='relevance',
            field=models.IntegerField(blank=True),
        ),
    ]
