# Generated by Django 5.1.6 on 2025-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_datapoint_likelihood_alter_datapoint_relevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
